### ISSUE TITLE
orbit.ks use of target as a variable in the target_angle function

### ISSUE THREAD

**Issue by blnk2007** [gisikw/ksprogramming#9]
More of a question than an issue. Since target is already a bound variable in kOS does trying to make a target variable parameter of target_angle function cause problems?

**Comment by gisikw** [comment]
Nope! Generally speaking, bound variables exist on the global scope, so using `target` will be fine. It's not a good practice though, and I'm going to try and avoid it in the future. But when trying to determine a value, kOS should look at the innermost context first, then look at the parent context, all the way up to the top global context, where the bound variables live. :)
